# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Growthcasts
description: >- # this means to ignore newlines until "baseurl:"
  Growthmarketing and Growth Hacking are new business strategies for startups that incorporate marketing within your product and core business values.
  Build growth right into the hard of your company, by using feedback and customer data to test, enhance your product, build a lean and sustainable business and become a master entrepreneur.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://growthcasts.co/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:  pmoorman
email: pieter@growthcasts.co

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Collections
collections_dir: collections
collections:
  - sales-header
  - intro
  - course
  - bonuses
  - prices
  - faq
  - testimonials
  - parts
  - slides
  - consulting-offers
  - videos

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - assets/js/core
  - assets/js/components
  - vendor

include:
  - _redirects
