# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Double
description: >- # this means to ignore newlines until "baseurl:"
  Growthmarketing and Growth Hacking are new business strategies for startups that incorporate marketing within your product and core business values.
  Build growth right into the hard of your company, by using feedback and customer data to test, enhance your product, build a lean and sustainable business and become a master entrepreneur.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://double-agency.com/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:  pmoorman
email: pieter@double-agency.co

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-target-blank

# Collections
collections_dir: collections
collections:
  posts:
    output: true
    permalink: /blog/:slug
  leadgen:
    output: true
    permalink: /:slug
  proposals:
    output: true
    permalink: /proposals/:slug
  case-studies:
    output: true
    permalink: /case-studies/:slug
  sales-header:
  intro:
  course:
  bonuses:
  prices:
  faq:
  testimonials:
  parts:
  slides:
  consulting-offers:
  videos:

defaults:
  - scope:
      path: ""
      type: "proposals"
    values:
      layout: "proposal"
  - scope:
      path: ""
      type: "case-studies"
    values:
      layout: "case-study"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - assets/js/core
  - assets/js/components
  - vendor

include:
  - _redirects

##
# From blog
##

# Social info
navigation: True # show the navbar links
subscribers: True # you need to connect an external service for this to work,
# if 'True' the submit button is disabled for now, but you can change that
# by editing `_includes/subscribe-form.html`
twitter: double-agency # replace by your username
facebook: Double # replace by your username

# Disqus
disqus: False
disqus_shortname: jekyller # replace with your disqus username

# Google Analytics
google_analytics: UA-69281367-1 # replace with your GA tracking identifier

# Permalinks
permalink: /:title
